#!/usr/bin/env python3
"""Populate a repo-root `.env` from live Terraform outputs.

Run after `terraform apply`:

    python scripts/gen_env.py

Reads `terraform output -json` from the `terraform/` directory and writes the
stack values local tooling/tests need. It also generates a random
TICKET_USERNAME/TICKET_PASSWORD and writes an empty TICKET_TOKEN - creating the
Cognito user and minting the token is left to the user (see the README / the
create-ticket skill). Overwrites `.env` silently; `.env` is gitignored so it
never reaches git.
"""
import json
import os
import secrets
import shutil
import string
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TF_DIR = REPO_ROOT / "terraform"
ENV_PATH = REPO_ROOT / ".env"

# Windows fallback location (terraform is not on PATH in this environment).
TERRAFORM_FALLBACK = r"C:\Program Files\terraform\terraform.exe"

HEADER = "# Generated by scripts/gen_env.py - do not edit; re-run after terraform apply"

# Terraform output name -> .env key. Order is preserved in the written file.
OUTPUT_MAP = {
    "api_base_url": "API_BASE_URL",
    "user_pool_id": "USER_POOL_ID",
    "user_pool_client_id": "USER_POOL_CLIENT_ID",
    "sns_topic_arn": "SNS_TOPIC_ARN",
    "dynamodb_table": "DYNAMODB_TABLE"
}


def find_terraform():
    """Locate the terraform binary: $TERRAFORM, PATH, then the Windows fallback."""
    override = os.environ.get("TERRAFORM")
    if override:
        return override
    found = shutil.which("terraform")
    if found:
        return found
    if Path(TERRAFORM_FALLBACK).exists():
        return TERRAFORM_FALLBACK
    fail("terraform binary not found - install it or set the TERRAFORM env var.")


def read_outputs():
    """Return the parsed `terraform output -json` object."""
    terraform = find_terraform()
    result = subprocess.run(
        [terraform, "output", "-json"],
        cwd=TF_DIR,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        fail("`terraform output` failed - run `terraform apply` first.\n"
             + result.stderr.strip())
    stdout = result.stdout.strip()
    if not stdout or stdout == "{}":
        fail("No Terraform outputs found - run `terraform apply` first.")
    return json.loads(stdout)


def build_env(outputs):
    """Map terraform outputs to {ENV_KEY: value}, warning on any missing key."""
    env = {}
    for tf_name, env_key in OUTPUT_MAP.items():
        if tf_name in outputs:
            env[env_key] = outputs[tf_name]["value"]
        else:
            print(f"warning: expected output '{tf_name}' missing - skipping",
                  file=sys.stderr)
    return env


def random_username():
    """A fresh, unique-ish plain username (the pool has no email alias)."""
    return "ticket-" + secrets.token_hex(6)


def random_password(length=16):
    """Alphanumeric password satisfying the pool policy (>=8, upper+lower+digit).

    Alphanumeric on purpose: no ',' or '=' so it stays a single safe token
    inside `--auth-parameters USERNAME=..,PASSWORD=..`.
    """
    alphabet = string.ascii_letters + string.digits
    while True:
        pw = "".join(secrets.choice(alphabet) for _ in range(length))
        if (any(c.islower() for c in pw)
                and any(c.isupper() for c in pw)
                and any(c.isdigit() for c in pw)):
            return pw


def add_ticket_credentials(env):
    """Append a random TICKET_USERNAME/TICKET_PASSWORD and an empty TICKET_TOKEN.

    We deliberately do not authenticate here: the random user does not yet exist
    in Cognito. Creating the user (with a permanent password) and minting the
    TICKET_TOKEN is the user's responsibility.
    """
    env["TICKET_USERNAME"] = random_username()
    env["TICKET_PASSWORD"] = random_password()
    env["TICKET_TOKEN"] = ""


def render_env(env):
    """Render the .env file contents (header + KEY=value lines)."""
    lines = [HEADER] + [f"{key}={value}" for key, value in env.items()]
    return "\n".join(lines) + "\n"


def fail(message):
    print(f"error: {message}", file=sys.stderr)
    sys.exit(1)


def main(env_path=ENV_PATH):
    outputs = read_outputs()
    env = build_env(outputs)
    add_ticket_credentials(env)
    Path(env_path).write_text(render_env(env), encoding="utf-8")
    print(f"Wrote {len(env)} values to {env_path}")


if __name__ == "__main__":
    main()
