#!/usr/bin/env python3
"""Populate a repo-root `.env` from live Terraform outputs.

Run after `terraform apply`:

    python scripts/gen_env.py

Reads `terraform output -json` from the `terraform/` directory and writes the
five stack values local tooling/tests need. Overwrites `.env` silently; `.env`
is gitignored so it never reaches git.
"""
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TF_DIR = REPO_ROOT / "terraform"
ENV_PATH = REPO_ROOT / ".env"

# Windows fallback location (terraform is not on PATH in this environment).
TERRAFORM_FALLBACK = r"C:\Program Files\terraform\terraform.exe"

HEADER = "# Generated by scripts/gen_env.py - do not edit; re-run after terraform apply"

# Terraform output name -> .env key. Order is preserved in the written file.
OUTPUT_MAP = {
    "api_base_url": "API_BASE_URL",
    "user_pool_id": "USER_POOL_ID",
    "user_pool_client_id": "USER_POOL_CLIENT_ID",
    "sns_topic_arn": "SNS_TOPIC_ARN",
    "dynamodb_table": "DYNAMODB_TABLE",
}


def find_terraform():
    """Locate the terraform binary: $TERRAFORM, PATH, then the Windows fallback."""
    override = os.environ.get("TERRAFORM")
    if override:
        return override
    found = shutil.which("terraform")
    if found:
        return found
    if Path(TERRAFORM_FALLBACK).exists():
        return TERRAFORM_FALLBACK
    fail("terraform binary not found - install it or set the TERRAFORM env var.")


def read_outputs():
    """Return the parsed `terraform output -json` object."""
    terraform = find_terraform()
    result = subprocess.run(
        [terraform, "output", "-json"],
        cwd=TF_DIR,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        fail("`terraform output` failed - run `terraform apply` first.\n"
             + result.stderr.strip())
    stdout = result.stdout.strip()
    if not stdout or stdout == "{}":
        fail("No Terraform outputs found - run `terraform apply` first.")
    return json.loads(stdout)


def build_env(outputs):
    """Map terraform outputs to {ENV_KEY: value}, warning on any missing key."""
    env = {}
    for tf_name, env_key in OUTPUT_MAP.items():
        if tf_name in outputs:
            env[env_key] = outputs[tf_name]["value"]
        else:
            print(f"warning: expected output '{tf_name}' missing - skipping",
                  file=sys.stderr)
    return env


def render_env(env):
    """Render the .env file contents (header + KEY=value lines)."""
    lines = [HEADER] + [f"{key}={value}" for key, value in env.items()]
    return "\n".join(lines) + "\n"


def fail(message):
    print(f"error: {message}", file=sys.stderr)
    sys.exit(1)


def main(env_path=ENV_PATH):
    outputs = read_outputs()
    env = build_env(outputs)
    Path(env_path).write_text(render_env(env), encoding="utf-8")
    print(f"Wrote {len(env)} values to {env_path}")


if __name__ == "__main__":
    main()
